openapi: "3.0.3"
info:
  version: "2023.9.17"
  title: Valos
  description: Example valorant web service

servers:
  - url: http://localhost:3000/
    description: Valorant information Api service local
  - url: https://valos.vercel.app/
    description: Valorant information Api service production

tags:
  - name: Content
    description: Valorant Content

paths:
  /api/contents:
    get:
      summary: Get contents
      operationId: contents
      deprecated: false
      tags:
        - Content
      responses:
        '200':
          description: Get contents successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetContentSuccessResponse"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetContentBadRequestResponse"

components:
  schemas:
    GetContentSuccessResponse:
      description: A response of the get a content successfully
      type: object
      required:
        - contents
      properties:
        contents:
          $ref: "./models/content.yaml#/components/schemas/Content"
    GetContentBadRequestResponse:
      description: A response of the get a content with bad request
      type: object
      required:
        - status
      properties:
        status:
          $ref: "./models/shared/errors.yaml#/components/schemas/BaseError"
